spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
server:
  port: 8090
seek:
  app:
    jwtSecret: seekSecretKey
    jwtExpirationMs: 86400000