server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver  
    url: jdbc:h2:mem:test
    #url: jdbc:h2:file:C:\Java\sts-4.3.1.RELEASE\workspace\spring_boot_community_web\database\h2\h2db
    username: sa
    password: 
  devtools:
    livereload:
      enabled: true
seek:
  app:
    jwtSecret: seekSecretKey
    jwtExpirationMs: 86400000