server:
  port: 8090
spring:
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver  
    url: jdbc:h2:mem:test
    #url: jdbc:h2:file:C:\Java\sts-4.3.1.RELEASE\workspace\spring_boot_community_web\database\h2\h2db
    username: sa
    password: 
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 1MB
upload:
  path:
    image:
      default:
        post: /upload/image/post/
      windows:
        post: C:/upload/image/post/
      linux:
        post: /home/dktmrorl/upload/image/post/
seek:
  app:
    jwtSecret: seekSecretKey
    jwtExpirationMs: 86400000